### ISSUE TITLE
Missing Tools From Toolbox List?

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#16]
Please review the list of tools in the [Toolbox](https://github.com/EAWF/Bitcoin-Merchants-Toolbox#the-toolbox).

Are there other tools that must/should be included?

**Comment by Septem151** [comment]
I think those tools are sufficient, but maybe "isBTCPaid" should be called "getBTCBalance"

Maybe "getPaymentRequest" could be changed to "getBTCInvoice" to better match the naming convention of the other tools.

**Comment by EAWF** [comment]
Yes, I agree! Good names!

**Comment by EAWF** [comment]
OK, no thoughts, comments, or requests, so I'm going to close this issue to get it off the books.

**Comment by EAWF** [comment]
There is also an opportunity for getBTCValue($btc) which converts number of coin to fiat value. Just another tool for the toolbox.
