### ISSUE TITLE
Branch For Each Programming Language?

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#18]
Should the Master Branch be treated as a pseudocode branch for the project, and a branch be created for each programming language?

If I understand branching correctly this would mean that each language would have its own branch of this repo. 

Is this something that should be done, or is it enough to create a separate sub-directory of the master branch for each language?

Your thoughts @Septem151, @coinables,  @PeterNSteinmetz ?

**Comment by EAWF** [comment]
Agreed! Great plan!

**Comment by Septem151** [comment]
> Would you like to take lead on this?

Sure, I can reorganize the repo.

**Comment by EAWF** [comment]
OK, you're assigned. I'll stand back and watch.  :smile:
