### ISSUE TITLE
Use Projects to manage ToDo and Workflow?

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#27]
I set up a project a while back, but am not sure how issues get automatically dropped in and flow through the project.

@Septem151 , do you know how to manage this?

**Comment by Septem151** [comment]
In my opinion, it's probably best to continue using the ToDo issue you've made in #23 and not use the Projects feature. I've never used it before so I don't know how to automate it. Up to you.

**Comment by EAWF** [comment]
OK, going to delete the project there and then leave it alone.
