### ISSUE TITLE
getBTCBalance

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#30]
In addition to the balance on the address, I think it would be good also have the user set a minimum number of confirmations to check for as for high ticket items, I would want to be able automate whether I'm ready to ship the goods or not.  So maybe:

getBTCBalance( $address , $confirmations = 1 ) as a default? 

@Septem151 , your thoughts?

**Comment by Septem151** [comment]
@EAWF The getBTCBalance function does this already with the $confirmations parameter:
```php
function getBTCBalance(string $address, int $confirmations = 0): string
```

I've defaulted it to 0 to show the balance including transactions currently unconfirmed and sitting in mempool. The usage, for getting a balance of the address including unconfirmed transactions, thus requires no parameter for confirmations as such:
```php
getBTCBalance($address);
```

This makes sense, as the number of confirmations is not given and so it is assumed to mean "include unconfirmed". If the merchant wanted to wait for a specific number of confirmations, they would use the function as such:
```php
getBTCBalance($address, $confirmations);
```

Where they can specify any value >= 0. My reasoning for this is that if you do not include an amount of confirmations, it is assumed that you don't care about the number of confirmations, so it defaults to 0 and includes pending/mempool transactions as well.

**Comment by EAWF** [comment]
Do we have this in the documentation somewhere?  If not, we need to make 
sure we add it.

**Comment by Septem151** [comment]
Yes, it is in the [documentation][1]

[1]: https://github.com/EAWF/Bitcoin-Merchants-Toolbox/tree/master/Toolbox/getBTCBalance#getbtcbalance
