### ISSUE TITLE
php-base58, php-gmp, and php-mcrypt not found.

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#41]
From @coinables : 
[I] Just tried on my local machine and I get the error that I don't have the right extensions. Not a big deal, but might want to add a note that the following PHP extensions need to be active: php-base58, php-gmp, and php-mcrypt.

**Comment by EAWF** [comment]
Yeah, that will be part of the installation instructions.  Are you able to install those extensions on your local machine/server?

**Comment by EAWF** [comment]
I use CentOS 7 minimal image and PHP 7.4 on the server you will have access to.
See my instruction cheat sheet at https://github.com/EAWF/Linux-Root-Tools/blob/master/ServerInit/php.md for details

**Comment by EAWF** [comment]
I'm wondering if that check should maybe be handled by a installation script so that the check doesn't happen each time the script loads.  Would save a little CPU time.

**Comment by Septem151** [comment]
@coinables If you are familiar with Docker, you can use this Dockerfile:
```Dockerfile
FROM php:7.3-cli

# Install dependencies for extensions
RUN apt-get update && apt-get install -y \
    libgmp-dev libmcrypt-dev libbase58-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install -j$(nproc) gmp \
    && pecl install mcrypt-1.0.3 \
    && pecl install base58-0.1.4 \
    && docker-php-ext-enable mcrypt base58

# Copy current directory of local machine into /usr/src/getBTC of docker image
COPY . /usr/src/getBTC
WORKDIR /usr/src/getBTC

# Run tests by default (Override this with --entrypoint php [docker-image-name] [location to PHP file])
CMD [ "php", "./Toolbox/tests/tests.php" ]
```

This is what I use for testing. Place the Dockerfile in the repo's root directory, then:
```sh
docker build -f [name_of_dockerfile] -t [any_name_you_want_for_image] .
```

To run the image, I use the following command which includes the "-v" flag to attach a volume so I can get test results back and make code changes without rebuilding the image every time:
```sh
docker run --rm -v $(pwd):/usr/src/getBTC [name_you_gave_to_image]
```
*Disclaimer*: I am using Ubuntu 20.04, not Windows, so [this][1] StackOverflow post may help you get the -v flag working.

If you wanted to run another php file other than test, you can override the entrypoint:
```sh
docker run --rm -v $(pwd):/usr/src/getBTC --entrypoint php [name_you_gave_to_image] [rest_of_php_command_arguments]
```

**Comment by EAWF** [comment]
Closing.
