### ISSUE TITLE
Generic Function Usage Docs Needed

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#42]
Need the generic function usage documentation. posted

**Comment by EAWF** [comment]
Usage Posted at [Toolbox/docs/README.md]

@Septem151 , please review and move if necessary.  As you know, I'm not good at placing documentation in the correct places. :smile:

**Comment by Septem151** [comment]
WIP

**Comment by Septem151** [comment]
Fixed in commit e97950b
