### ISSUE TITLE
namespace BTC; causes program failure in PHP 7.4

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#46]
Linux alpha.eawf.com 2.6.32-042stab139.1 #1 SMP Tue Jun 18 12:51:14 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.4.9 (cli) (built: Aug  4 2020 08:28:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

ran php getBTC.php to test and program failed.
commented out namespace BTC; and everything worked perfectly.

**Comment by Septem151** [comment]
Is there an error message for why it’s failing? Both docker tests and github actions tests run perfectly fine with namespacing.

**Comment by EAWF** [comment]
PHP Fatal error:  Uncaught Error: Call to undefined function getBTCRate() in /root/WIP/test.php:15
Stack trace:
#0 {main}
  thrown in /root/WIP/test.php on line 15

If I comment out the Namespace declaration, program runs fine.

Test.php
```php
<?php
 require_once 'getBTC.php';
 
 $Company = "Bitcoin Merchant's Toolbox Donation";
 $account = "Default";
 $label = $Company;
 $message = "Thanks for the donation!";
 $index = 0;
 $amount = 1.00;

 echo "\n".date(DATE_RFC2822);
 echo "\nCurrent BTC Exchange Rate:\n";
 $time_start = microtime(true);
 $result = getBTCRate(0);
 $time_end = microtime(true);
 $time = $time_end - $time_start;
 echo $result;
 echo " ($time secs.)\n\n";
 
 echo "$1.00 in BTC:\n";
 $time_start = microtime(true);
 $result = getBTCRate($amount);
 $time_end = microtime(true);
 $time = $time_end - $time_start;
 echo $result;
 echo " ($time secs.)\n\n";
 
 echo "New BTC Address:\n";
 $time_start = microtime(true);
 $address = getBTCAddress($account,$index );
 $time_end = microtime(true);
 $time = $time_end - $time_start;
 echo $address;
 echo " ($time secs.)\n\n";
 
 echo "Address Balance ($address):\n";
 $time_start = microtime(true);
 $result = getBTCBalance($address,0);
 $time_end = microtime(true);
 $time = $time_end - $time_start;
 echo $result;
 echo " ($time secs.)\n\n";

 echo "Address Balance ($address - 6 confirmations):\n";
 $time_start = microtime(true);
 $result = getBTCBalance($address,6);
 $time_end = microtime(true);
 $time = $time_end - $time_start;
 echo $result;
 echo " ($time secs.)\n\n";

 echo "BIP-21 String:\n";
 $time_start = microtime(true);
 $result = getBTCInvoice($account,$index,$amount,$label,$message);
 $time_end = microtime(true);
 $time = $time_end - $time_start;
 echo $result;
 echo " ($time secs.)\n\n";
?>
```

**Comment by EAWF** [comment]
Possible that a conditional statement can wrap this, but I have no idea what the condition would be that's causing this issue.

**Comment by EAWF** [comment]
Document a "comment out if you're having problems with this type of error" fix?

**Comment by EAWF** [comment]
OK, added  "namespace BTC;" at the top of test.php and before the require, and problem was resolved. 

We'll have to document this. Do I need to open this as a new issue, or just a ToDo?

**Comment by Septem151** [comment]
I removed the namespace entirely.
