### ISSUE TITLE
PHP Deriver

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#5]
The goal of this function, (and after seeing your code, it may be better to write it as a php class object), is for Merchants who want simple and quick. This should be a matter of:
USER INSTRUCTIONS:
1. Download and save the deriver.php file into a folder on your PHP include_path. This should be located in a folder which is NOT accessible by the public for security reasons.
2. Edit the file and change the:
   $extended_public_key variable to **YOUR** xpub, ypub, or zpub exported from your wallet.
3. At the top of your PHP page, add:
   require("derive.php");
4. Calculate your desired payment address $index however you wish, then derive the address using:
  $address = derive($index);

**Comment by Septem151** [comment]
As a bare minimum, the GMP extension for PHP will be required. The Elliptic Curve functions necessary for CKDpub (Scalar Multiplication and Scalar Addition) operate on Big Integers, which PHP cannot handle with precision via float values.

### [GMP](https://www.php.net/manual/en/book.gmp.php)
- Windows
  - [Find your php.ini file](https://www.templatemonster.com/blog/where-is-php-ini/)
  - Within the php.ini file, uncomment the gmp extension line: `;extension=gmp`
  - Restart Apache/web server
- Linux
  - `$ sudo apt-get install php-gmp`
  - Restart Apache/web server

### [Composer](https://getcomposer.org/)
As for the use of Composer, it would be difficult (but not impossible) to copy over classes and functions needed from the `/vendors/` folder into a single `derive.php` file. I will test this more later on tonight.

If using Composer is OK, then we could make this Deriver class a package with the name `eawf/deriver`. This would involve creating a separate repository on GitHub to host the package on (see [elliptic-php's composer.json file](https://github.com/simplito/elliptic-php/blob/master/composer.json) for example). To use the Deriver would be as simple as:
- Run the command `$ composer require eawf/deriver`
- Add `require_once('vendor/autoload.php');` at the top of your PHP page
- Create a new Deriver object: `$deriver = new Namespace\Deriver("xpub...");`, where `Namespace` is _to be determined_
- Calculate an address at a given index by calling: `$address = $deriver->derive($index);`

What are your thoughts on this? I believe it would make it a ton easier to continue using Composer and to have the Deriver be an installable Package.

**FYI**: If you want to test the current function (subject to change soon):
- Download the [Deriver](https://github.com/EAWF/Bitcoin-Merchants-Toolbox/tree/master/PHP/Deriver) folder
- In a command prompt, navigate to within the Deriver folder and run the command:
`$ composer install` **NOTE: You must have composer installed**
- Interact with the program through the command prompt:
  - `$ php src/index.php` - runs and prints a Test of the function
  - `$ php src/index.php [XPub] [Index]` - derives and prints an address at the given index

**Comment by EAWF** [comment]
IMHO:
* It's best to keep these tools self-contained in a drag and drop type format.
  - Base58(and Base58Check) should be one of these tools included as code within the tool, so as to avoid things like what you discovered I encountered in using a Base58 that was incorrect, plus it's easy enough to code and support.
* The requirements of the PHP environment(GMP) is OK because it's well documented in the PHP installation environment and if a normal person is going to get a server, they will have help from the provider to make sure it's installed.
* Platforms like MVC, NPM, and Composer are geared towards professional coders, way beyond the scope of the average person wishing to trade goods and services for bitcoin. There is too steep of a learning curve, and no way to easily verify every line of the code. Even I have extreme difficulty using them because if I'm going to use them, I have to be able to trust them and verify the code, and if I can't follow a strand of spaghetti on my plate to the other end, how do you expect me to follow spaghetti code? That's why I put the KISS codicil on the project.

**Comment by EAWF** [comment]
Don't know if you realized this or not, but the reason NOT to check for 
the index in the hardened range is that using an HD wallet, one can use 
hardened indexes for passwords. Turns out payment addresses make 
incredibly secure passwords that are easy to recreate by derivation and 
memorizing the index number because they will NEVER be used on the 
blockchain.

Hope you're doing well.  I'm hoping that you are poking around with the 
MIT App Inventor and creating a bitcoin derivation extension? I'm 
waiting to buy a copy from you.

Bob
