### ISSUE TITLE
Proposal to Consolidate to PHP version and Fork Other OS's

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#64]
I'm starting to feel more like this repo should become a PHP Only version that gets turned into a PHP Class of its own, and others can fork other versions for different programming languages.

I can see how it would be easier to maintain the repo that way.

Your thoughts: @Septem151 @coinables @PeterNSteinmetz ?

**Comment by Septem151** [comment]
I respect your decision to make the project PHP only. Sounds like a good idea.

**Comment by EAWF** [comment]
Still in proposal stage. While I have my thoughts, I'm still not convinced that it's the right way to go.  Looking for reasons why to keep it the way it is.  Not like we have a lot of pseudocode describing the processes yet. I'm not sure what impact changes in the pseudocode would have on others who are maintaining the other OS's and programming platforms, not to mention when other dependent resources used here have modifications or forks themselves.

**Comment by EAWF** [comment]
OK, read this: https://medium.com/@adamhjk/monorepo-please-do-3657e08a4b70 and am convinced that while my proposal would work in the short run, it would be much harder to deal with in the long run, so I'll delete this issue.
