### ISSUE TITLE
TODO: Extract & simplify private2public function

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#7]
Would be nice to extract and simplify the code necessary only for the private to public key conversion from itay/CryptoPHP's repo.

There may be other necessary functions required.

**Comment by Septem151** [comment]
see commit 2f61d21edb300b892be51539737421cfcafa247b

**Comment by EAWF** [comment]
Base58 and other functions are [here](https://github.com/EAWF/Bitcoin-Merchants-Toolbox/tree/master/Function%20Work%20Area)

**Comment by EAWF** [comment]
Awesome!  The math is starting to make more sense now that I can focus in closer on it.
I'll close this for now.
