### ISSUE TITLE
TODO: Build directory of Individual PHP functions

### ISSUE THREAD

**Issue by EAWF** [EAWF/Bitcoin-Merchants-Toolbox#8]
Isolate individual functions in a directory and prepare to build a concise library which is extremely easy to use.

**Comment by Septem151** [comment]
> Isolate individual functions in a directory to build a concise library

Does this mean we are no longer going for a singular file the user copy-pastes into their website directory to use? Correct me if I'm wrong, but this is what I thought we were going for:

```
example-site
|-- css
|   `-- [various files]
|-- images
|   `-- [various files]
|-- index.php
`-- btcderiver.php
```

Where `btcderiver.php` contains all code for the xpub->pubkey conversion (with a publicly facing `derive($xpub, $index)` function), and that can be used in, for example `index.php`, by putting `require('btcderiver.php');` at the top below the php starting tag.

**Comment by EAWF** [comment]
As I learn more about the derivation process, I am starting to see that my original thoughts aren't thought out well enough.
Account level exports are derived to the m/49'/0'/X'/ level and specifically to that "X" account.
In the case where you would want to route payments into different income streams, such as a different account for sales of products and also sales of services, you'd need two account level exports placed on the server.  I'm not quite sure if that's a good thing or a bad thing.
The option would be to export a parent key and chain code for m/49'/0'/ but in order to do that, we'd have to have the yprv and not the ypub, because you can't derive hardened parent key's and chaincodes from a ypub.  UNLESS I'm not understanding things correctly, so please correct me if I'm wrong.
Also, I had another thought...IF it is true that you can't derive private keys from public keys, then how is it that one can derive a public key from a private key derived from the ypub?

This is currently confusing me, because IF is impossible to derive a private key from a public key, which the ypub IS, what's the point of doing ecc math on the m/49'/0'/0'/0/0 derivation? Don't you already HAVE a public key to build the address off simply by running the parent chain code, the parent public key, and the index through SHA-512?  After all, CHD outputs a new parent chain code and matching parent public key, and wouldn't you just use the parent public key to convert to a payment address? Right?  Wrong?
Puzzling.

**Comment by EAWF** [comment]
# This is how I recommend one set up a domain on CentOS that uses PHP:
## Global Apache Directories
- **/var/www/**
  - the base directory for all apache reachable files
- **/var/www/html/**
  - the default "global" directory for the apache web server
  - I don't put anything in this directory so if someone browses to the hostname or IP address itself, they get the apache page.
- **/var/www/php/**
  - stores Serverwide PHP code that may be used by ALL virtual domains on the server. More about that below.
- **/var/www/graphics/**
  - stores Server-wide graphic images that may be used by ALL virtual domains on the server.
  - for example, I have domain.tld and also have another virtual domain foo.domain.tld, and both sites can use these graphics, such as a logo, or whatever else is needed on both virtual domains.
## Virtual Domain Directory Layout
- **/var/www/domainname/**
  - the base directory I create for a virtual host and I ALWAYS run domains from Virtual hosts because Let's Encrypt! LOVES to locate virtual hosts for adding certs, and doesn't like hosts in the default "global" apache directory for some reason.
- **/var/www/domainname/www/**
  - the document root(docroot) for the web domain.
  - **/var/www/domainname/www/index.html** OR
  - **/var/www/domainname/www/index.php** AND
  - **/var/www/domainname/www/styles.css** AND
  - **/var/www/domainname/www/toolbox.js** all live in this directory.
- **/var/www/domainname/graphics/**
  - holds virtual domain specific graphics files
- **/var/www/domainname/php/**
  - a directory I create for the PHP code that I don't want browser users to be able to access.
  - THIS is where the deriver will be stored.
## PHP Include Path
- This is an apache conf file entry that provides a specific path for PHP(running on localhost) to locate files that will not be directly accessable by web users. 
- Only the PHP engine can read them as includes or requires.
  - web users cannot access these files at all, so they are perfect storehouses for programs that contain passwords, keys, and other sensitive data.
- This is a security feature/tool that I use all the time.
- It looks like: **php_include_path = ".:/var/www/domainname/php:/var/www/php/"**
  - which means that when you require or include a file, say, "deriver.php":
    - look in the current directory first and run it if you find it. If not, then
    - look in /var/www/domainname/php and run it if you find it. If not, then
    - look in /var/www/php/ and run it if you find it. If not, throw an error. 
Although I set up a few more directories for totally different things, the above is the gist of the directory layout.

**Comment by EAWF** [comment]
oops...no, no change to your knowledge and direction of the project.  Will eventually be a class, BUT, in order to make sure we don't introduce bloat, I was thinking that if we gathered the functions that need to be included IN the library, in a side directory, it makes it easy to discover if we have bloat.

**Comment by Septem151** [comment]
> # This is how I recommend one set up a domain on CentOS that uses PHP:
> Global Apache Direc....

You'll have to forgive me for having very little knowledge about web servers. I'll look more into this. I'm assuming this is how I should configure a testing environment?

On a side note, I'm currently using a free host at http://phptesting.byethost24.com to test php code when I don't have access to php from the command line. This isn't necessarily relevant information and is moreso just a heads up about how I'm writing code for this project.

**Comment by EAWF** [comment]
I've been using this layout for the past 18 years and haven't had any problems.
If you're interested in pursuing more about web hosting, in the form of managed web hosting, let me know by email and I am willing to help you out.
